apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - image: gcr.io/nks-demo-242020/github.com/netapp/hci-nks-demo/static:latest
        name: static-demo
        ports:
        - containerPort: 80

