apiVersion: apps/v1
kind: Deployment
metadata:
  name: static
  labels:
    app: static
spec:
  replicas: 1
  selector:
    matchLabels:
      app: static
  template:
    metadata:
      labels:
        app: static
    spec:
      containers:
      - image: gcr.io/nks-test-249806/github.com/christhetrainer/hci-nks-demo:ae9daa1
        name: static-demo
        ports:
        - containerPort: 80

